{
 "title": "Homestats",
 "description": "Ambient data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "description": "Temperature in Celsius",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "stats",
     "query": "SELECT \"temperature_celsius\" FROM \"stats\"",
     "select": [
      [
       { "params": [ "temperature_celsius" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "description": "Relative humidity",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stats",
     "query": "SELECT \"humidity\" FROM \"stats\"",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ambient Light",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "stats",
     "query": "SELECT \"light\" FROM \"stats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "light" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "description": "CO2 parts per million",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stats",
     "query": "SELECT \"eCO2\" FROM \"stats\" ",
     "select": [
      [
       { "params": [ "eCO2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "UV" } },
   "yaxes": [
    { "format": "UV" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stats",
     "query": "SELECT \"uv\" FROM \"stats\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "uv" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TVOC",
   "type": "graph",
   "description": "Total volatile compounds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    {
     "measurement": "stats",
     "select": [
      [
       { "params": [ "TVOC" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}